# config.py

# --- SETTINGS WINDOW ---
SETTINGS_WINDOW_NAME = "⚙️ Pengaturan AetherPlayer"
SETTINGS_WIDTH = 400
SETTINGS_HEIGHT = 300

# --- DEFAULT STREAMING SETTINGS ---
DEFAULT_RTMP_URL = "rtmp://localhost/live"
DEFAULT_STREAM_KEY = "EmenKey123"
MAX_STREAM_KEY_LENGTH = 30
FPS = 30

# --- UKURAN WINDOW UTAMA ---
DEFAULT_WINDOW_WIDTH = 960
DEFAULT_WINDOW_HEIGHT = 720